/**
 * OpenAI Apps SDK Compliant Server Template
 * Automatically generated by FastMCP Builder
 * 
 * Follows OpenAI guidelines:
 * - Clear tool design (1 tool = 1 intention)
 * - Explicit schemas with Zod
 * - Proper error handling
 * - Security best practices
 * - Privacy compliant
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";

// ============================================
// SCHEMAS (OpenAI Guideline: Explicit Validation)
// ============================================

{{SCHEMAS}}

// ============================================
// SERVER SETUP
// ============================================

const server = new Server(
  {
    name: "{{APP_NAME}}",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// ============================================
// TOOL REGISTRATION (OpenAI Guideline: Clear Descriptions)
// ============================================

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
{{TOOLS_LIST}}
    ],
  };
});

// ============================================
// TOOL IMPLEMENTATION (OpenAI Guideline: Error Handling)
// ============================================

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
{{TOOL_CASES}}

      default:
        // OpenAI Guideline: Always handle unknown tools
        return {
          content: [
            {
              type: "text",
              text: \`❌ Unknown tool: \${name}\`,
            },
          ],
          isError: true,
        };
    }
  } catch (error) {
    // OpenAI Guideline: Proper error responses
    return {
      content: [
        {
          type: "text",
          text: \`❌ Error: \${error instanceof Error ? error.message : String(error)}\`,
        },
      ],
      isError: true,
    };
  }
});

// ============================================
// STARTUP (OpenAI Guideline: Graceful Error Handling)
// ============================================

async function main() {
  try {
    const transport = new StdioServerTransport();
    await server.connect(transport);
    console.error("✅ {{APP_NAME}} MCP Server running");
    console.error("📋 Follows OpenAI Apps SDK guidelines");
  } catch (error) {
    console.error("❌ Failed to start server:", error);
    process.exit(1);
  }
}

main().catch((error) => {
  console.error("❌ Fatal error:", error);
  process.exit(1);
});
